In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('df_data_virada.parquet')

In [3]:
df

,id_unidade,atendimento_id_unidade_ati,unidade,ati_id,procedimento_id,data_cobranca,data_realizacao,profissional_executante_id,quantidade,criado_por,...,justificativa,data_realizacao_item,data_pagamento,data_glosa,glosa,fir_MIN,fir_ultimo_updated_at,fir_valor_pago_fir,fir_qtd_faturamentos,data_virada
0,566812,273822,boavista,56681,592580,2020-03-03,2020-12-01,32,1.0000,atendimento,...,None,NaT,NaT,NaT,None,NaT,NaT,0.0,NaN,2020-12-25
1,579232,279252,boavista,57923,592580,2020-03-13,2020-12-09,23,1.0000,atendimento,...,None,NaT,NaT,NaT,None,NaT,NaT,0.0,NaN,2020-12-25
2,1449861,675091,olinda,144986,592991,2020-07-21,2020-08-08,6,1.0000,atendimento,...,None,NaT,NaT,NaT,None,NaT,NaT,0.0,NaN,NaT
5,660752,312662,boavista,66075,589478,2020-08-13,2020-08-01,4,1.0000,atendimento,...,None,2020-08-01,2020-10-15,NaT,None,2020-10-21 14:47:06,2020-10-21 14:47:06,120.0,1.0,NaT
6,660762,312662,boavista,66076,592486,2020-08-13,2020-08-01,4,1.0000,atendimento,...,None,2020-08-01,2020-10-15,NaT,None,2020-10-21 14:47:06,2020-10-21 14:47:06,6.6,1.0,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
916704,2593052,1042432,boavista,259305,590420,NaT,2023-09-02,124,1.0000,atendimento,...,None,NaT,NaT,NaT,None,NaT,NaT,0.0,NaN,NaT
916706,2593032,1042432,boavista,259303,590341,NaT,2023-09-02,124,1.0000,atendimento,...,None,NaT,NaT,NaT,None,NaT,NaT,0.0,NaN,NaT
916707,2593082,1042442,boavista,259308,592523,NaT,2023-09-02,124,1.0000,atendimento,...,None,NaT,NaT,NaT,None,NaT,NaT,0.0,NaN,NaT
916709,2593072,1042442,boavista,259307,592522,NaT,2023-09-02,124,1.0000,atendimento,...,None,NaT,NaT,NaT,None,NaT,NaT,0.0,NaN,NaT
916710,2593102,1042452,boavista,259310,592450,NaT,2023-09-02,124,1.0000,atendimento,...,None,NaT,NaT,NaT,None,NaT,NaT,0.0,NaN,NaT